name: Keep Streamlit App Alive

on:
  schedule:
    # Runs at 00:00 UTC every single day
    - cron: '0 0 * * *'
  # Allows you to manually trigger it whenever you want
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit URL
        run: |
          curl -I https://ai-recommender-lohith.streamlit.app/
